Fetching submission 180342...
Fetching code_submission_v2.py...
╭──────────────────────────────────────────────────────────────────────────────────────────── code_submission_v2.py ────────────────────────────────────────────────────────────────────────────────────────────╮
│     1 k=isinstance                                                                                                                                                                                            │
│     2 j=set                                                                                                                                                                                                   │
│     3 i=enumerate                                                                                                                                                                                             │
│     4 M=ord                                                                                                                                                                                                   │
│     5 c=list                                                                                                                                                                                                  │
│     6 I=ValueError                                                                                                                                                                                            │
│     7 R=Exception                                                                                                                                                                                             │
│     8 L=max                                                                                                                                                                                                   │
│     9 G=str                                                                                                                                                                                                   │
│    10 K=range                                                                                                                                                                                                 │
│    11 H=float                                                                                                                                                                                                 │
│    12 F=int                                                                                                                                                                                                   │
│    13 D=min                                                                                                                                                                                                   │
│    14 B=len                                                                                                                                                                                                   │
│    15 import argparse as AF,lzma as l,os,struct,re as E,time as P                                                                                                                                             │
│    16 for AG in('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','MKL_NUM_THREADS','NUMEXPR_NUM_THREADS','VECLIB_MAXIMUM_THREADS'):os.environ.setdefault(AG,'1')                                                      │
│    17 import numpy as A,uvicorn                                                                                                                                                                               │
│    18 from fastapi import FastAPI as m,HTTPException as AH                                                                                                                                                    │
│    19 from pydantic import BaseModel as n                                                                                                                                                                     │
│    20 from scipy.cluster.hierarchy import fcluster as o,linkage as p                                                                                                                                          │
│    21 from scipy.sparse import coo_matrix as u,csr_matrix as U,hstack as N                                                                                                                                    │
│    22 from scipy.sparse.linalg import eigsh                                                                                                                                                                   │
│    23 from sklearn.cluster import MiniBatchKMeans as x                                                                                                                                                        │
│    24 from sklearn.decomposition import TruncatedSVD as T                                                                                                                                                     │
│    25 from sklearn.feature_extraction.text import CountVectorizer as V,HashingVectorizer as O,TfidfVectorizer as g                                                                                            │
│    26 from sklearn.neighbors import NearestNeighbors as Q,kneighbors_graph                                                                                                                                    │
│    27 from sklearn.preprocessing import normalize as C                                                                                                                                                        │
│    28 import sklearn                                                                                                                                                                                          │
│    29 sklearn.set_config(working_memory=128)                                                                                                                                                                  │
│    30 AI=128                                                                                                                                                                                                  │
│    31 AJ=10                                                                                                                                                                                                   │
│    32 AK=3                                                                                                                                                                                                    │
│    33 AL=20000                                                                                                                                                                                                │
│    34 AM=192                                                                                                                                                                                                  │
│    35 W,X,J=8192,4096,48                                                                                                                                                                                      │
│    36 AN=.85                                                                                                                                                                                                  │
│    37 AO=.5                                                                                                                                                                                                   │
│    38 AP=130                                                                                                                                                                                                  │
│    39 AQ=12                                                                                                                                                                                                   │
│    40 AR=.2                                                                                                                                                                                                   │
│    41 AS=1                                                                                                                                                                                                    │
│    42 y=32                                                                                                                                                                                                    │
│    43 AT=28                                                                                                                                                                                                   │
│    44 AU=12                                                                                                                                                                                                   │
│    45 AV=.045                                                                                                                                                                                                 │
│    46 z=1                                                                                                                                                                                                     │
│    47 AW=.94                                                                                                                                                                                                  │
│    48 AX=.8                                                                                                                                                                                                   │
│    49 AY=.08                                                                                                                                                                                                  │
│    50 AZ=.03                                                                                                                                                                                                  │
│    51 v,Aa=40,300                                                                                                                                                                                             │
│    52 Ab=25                                                                                                                                                                                                   │
│    53 w=.001                                                                                                                                                                                                  │
│    54 Ac=1                                                                                                                                                                                                    │
│    55 A0=2                                                                                                                                                                                                    │
│    56 Ad=1                                                                                                                                                                                                    │
│    57 Ae=4                                                                                                                                                                                                    │
│    58 Af=1                                                                                                                                                                                                    │
│    59 b=.03                                                                                                                                                                                                   │
│    60 q,Ag=.25,.4                                                                                                                                                                                             │
│    61 Ah=.9                                                                                                                                                                                                   │
│    62 A1,Ai=.1,.32                                                                                                                                                                                            │
│    63 A2=6000                                                                                                                                                                                                 │
│    64 r=70                                                                                                                                                                                                    │
│    65 Aj=15000                                                                                                                                                                                                │
│    66 A3=12                                                                                                                                                                                                   │
│    67 Ak='첛겖奀一甶꣑娄両于一丂嫵鑧圌傪읝丕覇ꢥ糦뽈釫懙針ꢌ韂ꟙ좊墈괅帎쇴윾ꄡ獽峁榟민減贤괫迡뭮ꛠ嶯絔읩솧悲與攖쐌玓ꍓ珒嬙렾쬠쎣넖麷궑뾴毧戟쫖蹽疰打唴遨빂蚦잼鯜悅褈骼蟚襄ꘪ毸맚抔铊跃秠荚偘廨燯鉗漈际뀉뾉ꙅ惒愩蚷볒 │
│    68 S=None                                                                                                                                                                                                  │
│    69 Al=E.compile('http\\S+|www\\S+|https\\S+')                                                                                                                                                              │
│    70 Am=E.compile('@\\w+')                                                                                                                                                                                   │
│    71 An=E.compile('#(\\w+)')                                                                                                                                                                                 │
│    72 Ao=E.compile('[^\\w\\s]')                                                                                                                                                                               │
│    73 Ap=E.compile('\\s+')                                                                                                                                                                                    │
│    74 class Aq(n):texts:c[G]                                                                                                                                                                                  │
│    75 class Y(n):cluster_ids:c[F]                                                                                                                                                                             │
│    76 def Ar(text:G)->G:A=text;A=A.lower();A=Al.sub(' ',A);A=Am.sub(' ',A);A=An.sub('\\1',A);A=Ao.sub(' ',A);return Ap.sub(' ',A).strip()                                                                     │
│    77 As=(1024,1327,1),(19968,40959,2),(12352,12543,2),(44032,55215,2),(1536,1791,3),(1424,1535,4),(3584,3711,5),(2304,2431,6)                                                                                │
│    78 def A4(t):                                                                                                                                                                                              │
│    79     D=B(t)or 1;C=[0]*7                                                                                                                                                                                  │
│    80     for E in t:                                                                                                                                                                                         │
│    81         F=M(E)                                                                                                                                                                                          │
│    82         for(G,H,A)in As:                                                                                                                                                                                │
│    83             if G<=F<=H:C[A]+=1;break                                                                                                                                                                    │
│    84     A=L(K(1,7),key=lambda i:C[i]);return A if C[A]*8>=D else 0                                                                                                                                          │
│    85 def A5(lab,sid,lo=.05,hi=.4,pur=.55,ms=3):                                                                                                                                                              │
│    86     C=lab;C=A.asarray(C,A.int64).copy()                                                                                                                                                                 │
│    87     for E in K(1,7):                                                                                                                                                                                    │
│    88         G=sid==E;I=H(G.mean())if C.size else .0                                                                                                                                                         │
│    89         if I<lo or I>hi:continue                                                                                                                                                                        │
│    90         D=[]                                                                                                                                                                                            │
│    91         for J in A.unique(C[G]):                                                                                                                                                                        │
│    92             L=C==J                                                                                                                                                                                      │
│    93             if L.sum()>=ms and(sid[L]==E).mean()>=pur:D.append(F(J))                                                                                                                                    │
│    94         if B(D)>=2:C[A.isin(C,D)]=D[0]                                                                                                                                                                  │
│    95     return C                                                                                                                                                                                            │
│    96 def At(d,lab,Z,n,cap=3,lo=.012,hi=.12,ms=40):                                                                                                                                                           │
│    97     C=[]                                                                                                                                                                                                │
│    98     for G in A.unique(lab):                                                                                                                                                                             │
│    99         B=lab==G;D=F(B.sum())                                                                                                                                                                           │
│   100         if D<L(ms,F(lo*n))or D>F(hi*n):continue                                                                                                                                                         │
│   101         E=Z[B].mean(0);E/=A.linalg.norm(E)+1e-12;C.append((D*H((Z[B]@E).mean()),B))                                                                                                                     │
│   102     C.sort(key=lambda x:-x[0])                                                                                                                                                                          │
│   103     for(I,B)in C[:cap]:d[B]=-1.                                                                                                                                                                         │
│   104     return d                                                                                                                                                                                            │
│   105 def Au(docs,lab,thr=.7):                                                                                                                                                                                │
│   106     D=lab;D=A.asarray(D,A.int64).copy();E=A.unique(D);L=[' '.join(A.asarray(docs)[D==B][:80])for B in E]                                                                                                │
│   107     try:H=C(g(max_features=4000,stop_words='english',dtype=A.float32).fit_transform(L))                                                                                                                 │
│   108     except I:return D                                                                                                                                                                                   │
│   109     G=(H@H.T).toarray();A.fill_diagonal(G,0);J,K=divmod(F(G.argmax()),B(E))                                                                                                                             │
│   110     if G[J,K]>=thr:D[D==E[K]]=E[J]                                                                                                                                                                      │
│   111     return D                                                                                                                                                                                            │
│   112 def Av(X):                                                                                                                                                                                              │
│   113     X=A.asarray(X,A.float32)                                                                                                                                                                            │
│   114     if D(X.shape)<3:return .0                                                                                                                                                                           │
│   115     X=X-X.mean(0,keepdims=True);return H(T(n_components=1,random_state=42).fit(X).explained_variance_ratio_[0])                                                                                         │
│   116 def s(X,n=1):                                                                                                                                                                                           │
│   117     X=A.asarray(X,A.float32)                                                                                                                                                                            │
│   118     if D(X.shape)<3 or n<1:return C(X)                                                                                                                                                                  │
│   119     X=X-X.mean(0,keepdims=True);n=D(F(n),X.shape[1]-1,X.shape[0]-1)                                                                                                                                     │
│   120     if n<1:return C(X)                                                                                                                                                                                  │
│   121     B=T(n_components=n,random_state=42).fit(X);return C(X-B.inverse_transform(B.transform(X)))                                                                                                          │
│   122 def Aw(docs,sif=0):                                                                                                                                                                                     │
│   123     J=docs                                                                                                                                                                                              │
│   124     try:K=V(min_df=AK,stop_words='english',dtype=A.int32,max_features=AL);K.fit(J)                                                                                                                      │
│   125     except I:return                                                                                                                                                                                     │
│   126     F=K.vocabulary_                                                                                                                                                                                     │
│   127     if B(F)<10:return                                                                                                                                                                                   │
│   128     c=K.build_analyzer();G,Q=[],[]                                                                                                                                                                      │
│   129     for R in J:                                                                                                                                                                                         │
│   130         S=[F[A]for A in c(R)if A in F]                                                                                                                                                                  │
│   131         for(U,W)in i(S):                                                                                                                                                                                │
│   132             for X in S[U+1:U+1+AJ]:G.append(W);Q.append(X);G.append(X);Q.append(W)                                                                                                                      │
│   133     if not G:return                                                                                                                                                                                     │
│   134     M=B(F);E=u((A.ones(B(G),dtype=A.float32),(G,Q)),shape=(M,M)).tocsr();E.sum_duplicates();Y=E.sum()                                                                                                   │
│   135     if Y<=0:return                                                                                                                                                                                      │
│   136     d=A.asarray(E.sum(axis=1)).ravel();e=A.asarray(E.sum(axis=0)).ravel();E=E.tocoo()                                                                                                                   │
│   137     with A.errstate(divide='ignore',invalid='ignore'):N=A.log(E.data*Y/(d[E.row]*e[E.col]+1e-12)+1e-12)                                                                                                 │
│   138     N[~A.isfinite(N)]=.0;O=N>0                                                                                                                                                                          │
│   139     if not O.any():return                                                                                                                                                                               │
│   140     Z=u((N[O],(E.row[O],E.col[O])),shape=(M,M)).tocsr();R=D(AI,L(2,D(Z.shape)-1));a=C(T(n_components=R,random_state=42).fit_transform(Z))                                                               │
│   141     if sif:b=K.transform(J).astype(A.float32);P=A.asarray(b.sum(0)).ravel();P=P/L(H(P.sum()),1.);f=(w/(w+P)).astype(A.float32);return C(A.asarray(b.multiply(f)@a))                                     │
│   142     h=g(vocabulary=F,stop_words='english',sublinear_tf=True,dtype=A.float32);return C(h.fit_transform(J)@a)                                                                                             │
│   143 def t(docs):                                                                                                                                                                                            │
│   144     H=B(docs)                                                                                                                                                                                           │
│   145     for J in({True:2,False:1}[H>=50],1):                                                                                                                                                                │
│   146         F=[]                                                                                                                                                                                            │
│   147         for K in(dict(stop_words='english',ngram_range=(1,2),analyzer='word'),dict(analyzer='char_wb',ngram_range=(3,5))):                                                                              │
│   148             try:                                                                                                                                                                                        │
│   149                 E=g(max_features=100000,min_df=J,max_df=.5,sublinear_tf=True,dtype=A.float32,**K).fit_transform(docs)                                                                                   │
│   150                 if E.shape[1]>=2:F.append(C(E))                                                                                                                                                         │
│   151             except I:continue                                                                                                                                                                           │
│   152         if F:                                                                                                                                                                                           │
│   153             E=N(F).tocsr()if B(F)>1 else F[0];G=D(AM,E.shape[1]-1,L(2,E.shape[0]-1))                                                                                                                    │
│   154             if G<2:return                                                                                                                                                                               │
│   155             return C(T(n_components=G,random_state=42).fit_transform(E))                                                                                                                                │
│   156 def Ax():                                                                                                                                                                                               │
│   157     global S                                                                                                                                                                                            │
│   158     if S is not None:return S                                                                                                                                                                           │
│   159     G=Ak                                                                                                                                                                                                │
│   160     if not G:return                                                                                                                                                                                     │
│   161     H=l.decompress(B2(G));I=(W+X)*J;D=(I+3)//4;L=A.frombuffer(H[:D],A.uint8);C=A.zeros(B(L)*4,A.uint8)                                                                                                  │
│   162     for M in K(4):C[M::4]=L>>2*M&3                                                                                                                                                                      │
│   163     C=C[:I].reshape(W+X,J);N=A.frombuffer(H[D:D+J*16],A.float32).reshape(J,4);E=A.empty(C.shape,A.float32)                                                                                              │
│   164     for F in K(J):E[:,F]=N[F][C[:,F]]                                                                                                                                                                   │
│   165     S=E;return E                                                                                                                                                                                        │
│   166 def Ay(docs):                                                                                                                                                                                           │
│   167     E=docs;F=Ax()                                                                                                                                                                                       │
│   168     if F is None:return                                                                                                                                                                                 │
│   169     try:                                                                                                                                                                                                │
│   170         I=O(n_features=W,ngram_range=(1,2),analyzer='word',alternate_sign=False,norm=None,dtype=A.float32);J=O(n_features=X,ngram_range=(3,5),analyzer='char_wb',alternate_sign=False,norm=None,dtype=A │
│   171         for D in K(0,B(E),4000):G=N([I.transform(E[D:D+4000]),J.transform(E[D:D+4000])]).tocsr();G.data=A.log1p(G.data).astype(A.float32);H[D:D+4000]=A.asarray(C(G)@F,dtype=A.float32)                 │
│   172         return C(H)                                                                                                                                                                                     │
│   173     except R:return                                                                                                                                                                                     │
│   174 def Az(Z,k=None,alpha=None,iters=None):                                                                                                                                                                 │
│   175     E=iters;B=alpha;k=AQ if k is None else k;B=AR if B is None else B;E=AS if E is None else E;G=Z.shape[0];H=D(k+1,G-1)                                                                                │
│   176     if H<2:return Z                                                                                                                                                                                     │
│   177     J,L=Q(n_neighbors=H,metric='cosine').fit(Z).kneighbors(Z)                                                                                                                                           │
│   178     for J in K(E):                                                                                                                                                                                      │
│   179         I=A.empty_like(Z)                                                                                                                                                                               │
│   180         for F in K(0,G,2000):I[F:F+2000]=Z[L[F:F+2000,1:]].mean(axis=1)                                                                                                                                 │
│   181         Z=C((1.-B)*Z+B*I)                                                                                                                                                                               │
│   182     return Z                                                                                                                                                                                            │
│   183 def A_(Z,dim=None,k=15):                                                                                                                                                                                │
│   184     B=dim;B=y if B is None else B;E=Z.shape[0]                                                                                                                                                          │
│   185     if E<50 or B<=0:return                                                                                                                                                                              │
│   186     try:F=Q(n_neighbors=D(k,E-1),metric='cosine').fit(Z).kneighbors_graph(Z,mode='connectivity');F=(F+F.T>0).astype(A.float32);G=A.asarray(F.sum(axis=1)).ravel();G[G==0]=1.;H=1./A.sqrt(G);I=U(F.multi │
│   187     except R:return                                                                                                                                                                                     │
│   188 def B0(Z,k=None,sample=1500):k=A3 if k is None else k;F=Q(n_neighbors=D(k+1,B(Z)-1),metric='cosine').fit(Z);E=F.kneighbors(Z)[0][:,1:];C=A.random.default_rng(0).choice(B(Z),D(sample,B(Z)),replace=Fal │
│   189 def B1(rel):B=H(A.clip((rel-A1)/(Ai-A1),.0,1.));return F(round(v+(Aa-v)*B)),H(q+(Ag-q)*B)                                                                                                               │
│   190 def h(docs,n_total,mask):                                                                                                                                                                               │
│   191     C=docs                                                                                                                                                                                              │
│   192     try:                                                                                                                                                                                                │
│   193         G=t(C)                                                                                                                                                                                          │
│   194         if G is None:raise I                                                                                                                                                                            │
│   195         K=L(2,D(60,B(C)//40));H=x(K,random_state=0,n_init=3).fit_predict(G)                                                                                                                             │
│   196     except R:H=A.zeros(B(C),A.int64)                                                                                                                                                                    │
│   197     E,J=[],0                                                                                                                                                                                            │
│   198     for M in mask:                                                                                                                                                                                      │
│   199         if M:E.append(-1)                                                                                                                                                                               │
│   200         else:E.append(F(H[J]));J+=1                                                                                                                                                                     │
│   201     return E                                                                                                                                                                                            │
│   202 def B2(s):                                                                                                                                                                                              │
│   203     B=A=0;C=bytearray()                                                                                                                                                                                 │
│   204     for D in s:                                                                                                                                                                                         │
│   205         B=B<<15|M(D)-19968;A+=15                                                                                                                                                                        │
│   206         while A>=8:A-=8;C.append(B>>A&255)                                                                                                                                                              │
│   207     return bytes(C)                                                                                                                                                                                     │
│   208 Z=8e1                                                                                                                                                                                                   │
│   209 A6,A7,BW=8192,4096,24                                                                                                                                                                                   │
│   210 B3,B4=80,.4                                                                                                                                                                                             │
│   211 B5,BX,BY=4.,.5,13e1                                                                                                                                                                                     │
│   212 A8,B6,BZ=6000,4000,32                                                                                                                                                                                   │
│   213 Ba,B7,Bb=.4,.6,0                                                                                                                                                                                        │
│   214 A9,AA,Bc,Bd=.5,1.,1.,1.                                                                                                                                                                                 │
│   215 B8=E.compile('[^\\w\\s]')                                                                                                                                                                               │
│   216 B9,BA,BB,BC=.35,8000,.35,8000                                                                                                                                                                           │
│   217 BD='丁婸凴보Ꙛ一伹꣖鉠币刄蘀一噧ꐳ樜暈꾨丁丅쥜侇ꈘꕘ烕墴畻붴ꗹ緉篙뫅롅꒪搞厤鍮礽鬩鬶喨뒐猡犸茔쫎坐茷蟉廝熥籥ꬷ蜲浇鞒ꀝ膗뻴甕髃짣弩芀姠딟抐秎ꎙ읰膎뚑刔댞儜챗搑芭闡錾誧經烚꺮釳鑯뾠溯膀揖衾罄魘璘숈芒賶쀢鼴싆 │
│   218 a=E.compile('https?://\\S+|www\\.\\S+')                                                                                                                                                                 │
│   219 BE=E.compile('^rt\\s+',E.IGNORECASE)                                                                                                                                                                    │
│   220 d=E.compile('@\\w+')                                                                                                                                                                                    │
│   221 AB=E.compile('#(\\w+)')                                                                                                                                                                                 │
│   222 BF=E.compile('(?<=[a-z0-9])(?=[A-Z])')                                                                                                                                                                  │
│   223 BG=E.compile('(.)\\1{2,}')                                                                                                                                                                              │
│   224 e=E.compile('\\s+')                                                                                                                                                                                     │
│   225 BH=E.compile("[^\\W\\d_][\\w\\-']*",E.UNICODE)                                                                                                                                                          │
│   226 BI=j('a an the of for and or to in on with by from at as is are be been we our us\nthis that it its i you your he she they them his her their what which who when where how\nall any both each few more │
│   227 def BJ(t):                                                                                                                                                                                              │
│   228     if not k(t,G):t=G(t)                                                                                                                                                                                │
│   229     t=t.lower();t=a.sub(' ',t);t=d.sub(' ',t);t=AB.sub('\\1',t);return not e.sub(' ',B8.sub(' ',t)).strip()                                                                                             │
│   230 def AC(t):                                                                                                                                                                                              │
│   231     if not k(t,G):t=G(t)                                                                                                                                                                                │
│   232     t=a.sub(' ',t);t=BE.sub(' ',t);t=d.sub(' ',t);t=AB.sub('\\1',t);t=BF.sub(' ',t);t=BG.sub('\\1\\1',t);return e.sub(' ',t).strip()[:B6]                                                               │
│   233 def BK(t):return[A for A in(A.group(0).lower()for A in BH.finditer(t))if B(A)>2 and A not in BI]                                                                                                        │
│   234 def AD(C,k1=3.,b=.75):C=C.tocsr().astype(A.float32);D=A.asarray(C.sum(1)).ravel();F=L(H(D.mean()),1e-09);E=A.asarray((C>0).sum(0)).ravel();G=A.log(1.+(C.shape[0]-E+.5)/(E+.5)).astype(A.float32);B=C.t │
│   235 def BL(P,title=False):                                                                                                                                                                                  │
│   236     K,L=(B9,BA)if title else(BB,BC);E=[]                                                                                                                                                                │
│   237     try:E.append(AD(V(ngram_range=(1,2),min_df=2,max_df=.95,max_features=20000,stop_words='english',dtype=A.float32).fit_transform(P)))                                                                 │
│   238     except I:pass                                                                                                                                                                                       │
│   239     try:                                                                                                                                                                                                │
│   240         G=AD(V(analyzer='char_wb',ngram_range=(3,5),min_df=2,max_df=.95,max_features=L,dtype=A.float32).fit_transform(P))                                                                               │
│   241         if G.shape[1]>0:E.append(G*K)                                                                                                                                                                   │
│   242     except I:pass                                                                                                                                                                                       │
│   243     if not E:return                                                                                                                                                                                     │
│   244     H=C(E[0]if B(E)==1 else N(E).tocsr());J=F(D(192,H.shape[1]-1,B(P)-1));return C(T(J,random_state=0).fit_transform(H)).astype(A.float32)if J>=2 else None                                             │
│   245 def BM(texts):                                                                                                                                                                                          │
│   246     K=[BK(AC(A))for A in texts];L={}                                                                                                                                                                    │
│   247     for E in K:                                                                                                                                                                                         │
│   248         for M in j(E):L[M]=L.get(M,0)+1                                                                                                                                                                 │
│   249     G=[A for(A,B)in L.items()if B>=3]                                                                                                                                                                   │
│   250     G.sort(key=lambda w:(-L[w],w))                                                                                                                                                                      │
│   251     if B(G)>6000:G=G[:6000]                                                                                                                                                                             │
│   252     if B(G)<50:return                                                                                                                                                                                   │
│   253     Q={B:A for(A,B)in i(G)};N,S=[],[]                                                                                                                                                                   │
│   254     for(X,E)in i(K):                                                                                                                                                                                    │
│   255         for M in j(E):                                                                                                                                                                                  │
│   256             V=Q.get(M)                                                                                                                                                                                  │
│   257             if V is not None:N.append(X);S.append(V)                                                                                                                                                    │
│   258     if not N:return                                                                                                                                                                                     │
│   259     O=U((A.ones(B(N),A.float32),(N,S)),shape=(B(K),B(Q)));I=(O.T@O).toarray().astype(A.float32);A.fill_diagonal(I,.0);W=H(I.sum())                                                                      │
│   260     if W<=0:return                                                                                                                                                                                      │
│   261     Y=I.sum(1,keepdims=True);Z=I.sum(0,keepdims=True)                                                                                                                                                   │
│   262     with A.errstate(divide='ignore',invalid='ignore'):J=A.log(I*(W/(Y*Z+1e-12))+1e-12,dtype=A.float32)                                                                                                  │
│   263     del I;J[~A.isfinite(J)]=.0;A.maximum(J,.0,out=J);E=F(D(96,B(Q)-1))                                                                                                                                  │
│   264     if E<2:return                                                                                                                                                                                       │
│   265     a=C(T(E,random_state=0).fit_transform(J));del J;b=A.log(B(K)/(1.+A.asarray(O.sum(0)).ravel()));P=C(O.multiply(b).tocsr()@a).astype(A.float32);R=A.abs(P).sum(1)<1e-09                               │
│   266     if R.any():P[R]=A.random.RandomState(0).normal(size=(F(R.sum()),P.shape[1]))*.001                                                                                                                   │
│   267     return P                                                                                                                                                                                            │
│   268 def BN(s):                                                                                                                                                                                              │
│   269     A=0                                                                                                                                                                                                 │
│   270     for B in s[2:]:A=A<<15|M(B)-19968                                                                                                                                                                   │
│   271     return A.to_bytes(M(s[0])-19968<<15|M(s[1])-19968,'big')                                                                                                                                            │
│   272 def BO(title=False):C=l.decompress(BN(BD));B,D,M=struct.unpack('<IIB',C[:9]);J=A.cumsum(A.frombuffer(C[9:9+2*B],A.uint16).astype(A.int64))-1;G=B*D;E=(G+1)//2;H=A.frombuffer(C[9+2*B:9+2*B+E],A.uint8); │
│   273 def BP(texts,title=False):                                                                                                                                                                              │
│   274     F=texts                                                                                                                                                                                             │
│   275     try:                                                                                                                                                                                                │
│   276         G=BO(title);J=O(n_features=A6,ngram_range=(1,2),analyzer='word',alternate_sign=False,norm=None,dtype=A.float32);L=O(n_features=A7,ngram_range=(3,5),analyzer='char_wb',alternate_sign=False,nor │
│   277         for D in K(0,B(F),4000):I=[BS(A)for A in F[D:D+4000]];E=N([J.transform(I),L.transform(I)]).tocsr();E.data=A.log1p(E.data).astype(A.float32);H[D:D+4000]=A.asarray(C(E)@G,dtype=A.float32);del E │
│   278         return C(H)                                                                                                                                                                                     │
│   279     except R:return                                                                                                                                                                                     │
│   280 BQ=E.compile('[^\\w\\s一-鿿]')                                                                                                                                                                          │
│   281 BR=E.compile('&\\w+;')                                                                                                                                                                                  │
│   282 def BS(t):                                                                                                                                                                                              │
│   283     if not k(t,G):t=G(t)                                                                                                                                                                                │
│   284     t=a.sub(' ',t);t=d.sub(' ',t);t=t.lower();t=BR.sub(' ',t);t=BQ.sub(' ',t);return e.sub(' ',t).strip()[:1000]                                                                                        │
│   285 def BT(Z,k=20,alpha=.4,iters=4):                                                                                                                                                                        │
│   286     F=alpha                                                                                                                                                                                             │
│   287     try:                                                                                                                                                                                                │
│   288         G=Q(n_neighbors=D(k+1,B(Z)-1),metric='cosine').fit(Z).kneighbors(Z)[1][:,1:];E=Z                                                                                                                │
│   289         for H in K(iters):E=C((1-F)*E+F*E[G].mean(1))                                                                                                                                                   │
│   290         return E.astype(A.float32)                                                                                                                                                                      │
│   291     except R:return Z                                                                                                                                                                                   │
│   292 def BU(Z,k=12,sample=1500):E=Q(n_neighbors=D(k+1,B(Z)-1),metric='cosine').fit(Z).kneighbors(Z)[0][:,1:];F=H(E[:,-1].mean());C=A.random.default_rng(0).choice(B(Z),D(sample,B(Z)),replace=False);G=1.-Z[ │
│   293 def BV(texts):                                                                                                                                                                                          │
│   294     L=texts                                                                                                                                                                                             │
│   295     try:                                                                                                                                                                                                │
│   296         S=P.time();G=B(L);V=G>A8;M=A.sort(A.random.default_rng(0).choice(G,A8,replace=False))if V else A.arange(G);W=[L[A]for A in M];e=[AC(A)for A in W];I=[];X=BL(e,True)                             │
│   297         if X is not None and A9>0:I.append(C(X)*A9)                                                                                                                                                     │
│   298         if P.time()-S<Z*.45 and AA>0:                                                                                                                                                                   │
│   299             Y=BM(W)                                                                                                                                                                                     │
│   300             if Y is not None:I.append(C(Y)*AA)                                                                                                                                                          │
│   301         N=BP(L,True)if P.time()-S<Z*.62 else None                                                                                                                                                       │
│   302         if N is not None:I.append(C(N[M])*B5)                                                                                                                                                           │
│   303         if not I:return                                                                                                                                                                                 │
│   304         O=C(A.hstack(I))if B(I)>1 else I[0]                                                                                                                                                             │
│   305         if P.time()-S<Z*.62:O=BT(O,alpha=B7)                                                                                                                                                            │
│   306         k,f=BU(O);a=A.fromiter((BJ(A)for A in L),bool,G);g,b=F(B3),H(B4);c=o(p(O,'average','cosine'),g,'maxclust').astype(A.int64)                                                                      │
│   307         if not V:E,T=c,f[:,-1]                                                                                                                                                                          │
│   308         else:                                                                                                                                                                                           │
│   309             U=C(N)if N is not None else None                                                                                                                                                            │
│   310             if U is None:return                                                                                                                                                                         │
│   311             h=Q(n_neighbors=D(5,B(M)),metric='cosine').fit(U[M]);E=A.empty(G,A.int64);T=A.empty(G,A.float32)                                                                                            │
│   312             for J in K(0,G,5000):i,j=h.kneighbors(U[J:J+5000]);E[J:J+5000]=[A.bincount(B).argmax()for B in c[j]];T[J:J+5000]=i[:,-1]                                                                    │
│   313         if b>0:d=A.argsort(-T)[:F(G*b)];E[d]=A.arange(1000000,1000000+B(d))                                                                                                                             │
│   314         l,E=A.unique(E,return_inverse=True);E=E.astype(A.int64)                                                                                                                                         │
│   315         if a.any():E[a]=-1                                                                                                                                                                              │
│   316         return[F(A)for A in E]                                                                                                                                                                          │
│   317     except R:return                                                                                                                                                                                     │
│   318 def RED(lab,Z,t=.76,ms=5):                                                                                                                                                                              │
│   319     lab=A.asarray(lab,A.int64).copy();ids,c=A.unique(lab,return_counts=True);Cc,Nn=ids[c>=ms],ids[c<ms]                                                                                                 │
│   320     if B(Cc)<1 or B(Nn)<1:return lab                                                                                                                                                                    │
│   321     M=C(A.stack([Z[lab==i].mean(0)for i in Cc]))                                                                                                                                                        │
│   322     for i in Nn:                                                                                                                                                                                        │
│   323         m=lab==i;s=Z[m]@M.T;bb,v=s.argmax(1),s.max(1)                                                                                                                                                   │
│   324         for jj,k in enumerate(A.where(m)[0]):                                                                                                                                                           │
│   325             if v[jj]>=t:lab[k]=Cc[bb[jj]]                                                                                                                                                               │
│   326     return lab                                                                                                                                                                                          │
│   327 def MNN(l,Z):                                                                                                                                                                                           │
│   328     l=A.asarray(l,A.int64).copy()                                                                                                                                                                       │
│   329     for t,ms,r in((.8,1,1),(.86,5,4)):                                                                                                                                                                  │
│   330         for _ in K(r):                                                                                                                                                                                  │
│   331             ids,c=A.unique(l,return_counts=True);s=ids[c<=ms]                                                                                                                                           │
│   332             if B(s)<2:break                                                                                                                                                                             │
│   333             Cc=C(A.stack([Z[l==i].mean(0)for i in s]))                                                                                                                                                  │
│   334             d,I=Q(n_neighbors=2,metric="cosine").fit(Cc).kneighbors(Cc);hit=0                                                                                                                           │
│   335             for a_ in K(B(s)):                                                                                                                                                                          │
│   336                 b_=F(I[a_,1])                                                                                                                                                                           │
│   337                 if 1.-d[a_,1]>=t and F(I[b_,1])==a_ and s[a_]<s[b_]:l[l==s[b_]]=s[a_];hit=1                                                                                                             │
│   338             if not hit:break                                                                                                                                                                            │
│   339             _,l=A.unique(l,return_inverse=True)                                                                                                                                                         │
│   340     return l                                                                                                                                                                                            │
│   341                                                                                                                                                                                                         │
│   342 def cluster_texts(texts:c[G])->c[F]:                                                                                                                                                                    │
│   343     d=texts;u=P.perf_counter();U=B(d)                                                                                                                                                                   │
│   344     if U<3:return c(K(U))                                                                                                                                                                               │
│   345     A1=[Ar(A)for A in d];V=[B(A)==0 for A in A1];I=[A for(A,B)in zip(A1,V)if not B]                                                                                                                     │
│   346     if B(I)<3:return[0]*U                                                                                                                                                                               │
│   347     try:                                                                                                                                                                                                │
│   348         J=B(I)                                                                                                                                                                                          │
│   349         if J>Aj:                                                                                                                                                                                        │
│   350             try:A6=g(max_features=60000,min_df=3,max_df=.5,stop_words='english',ngram_range=(1,2),sublinear_tf=True,dtype=A.float32).fit_transform(I);AG=D(128,A6.shape[1]-1,J-1);G=C(T(n_components=L( │
│   351             except R:G=t(I)                                                                                                                                                                             │
│   352             if G is None:return h(I,U,V)                                                                                                                                                                │
│   353             S=L(2,D(F(A.sqrt(J/2)*2),400));E=x(n_clusters=D(S,J-1),random_state=42,n_init=3,batch_size=4096,max_iter=100).fit_predict(G).astype(A.int64);AH=Q(n_neighbors=D(A3+1,J-1),metric='euclidean │
│   354             if W>0:O=i.copy();O[e>0]=-1.;M=A.argpartition(-O,W-1)[:W];M=M[O[M]>=0];E[M]=A.arange(1000000,1000000+B(M))                                                                                  │
│   355             v,E=A.unique(E,return_inverse=True);X,f=[],0                                                                                                                                                │
│   356             for w in V:                                                                                                                                                                                 │
│   357                 if w:X.append(-1)                                                                                                                                                                       │
│   358                 else:X.append(F(E[f]));f+=1                                                                                                                                                             │
│   359             return X                                                                                                                                                                                    │
│   360         A7=[B(A)for A in I];A8=[A for A in A7 if A>=40];AI=H(A.median(A8 if B(A8)>=50 else A7));AJ=H(A.mean(['\n'in A for A in d]));AK=H(A.mean(['http'in A.lower()or'www.'in A.lower()for A in d]));N= │
│   361         if N:                                                                                                                                                                                           │
│   362             AA=BV(d)                                                                                                                                                                                    │
│   363             if AA is not None:return AA                                                                                                                                                                 │
│   364         Z=t(I);a=Av(Z)if Z is not None else .0;j=not N and a>AV;Y=[];k=Aw(I,sif=N)                                                                                                                      │
│   365         if k is not None:                                                                                                                                                                               │
│   366             if N:l=Ad                                                                                                                                                                                   │
│   367             elif j:l=Ae                                                                                                                                                                                 │
│   368             elif a<b:l=1                                                                                                                                                                                │
│   369             else:l=3 if 230<AI<330 else A0                                                                                                                                                              │
│   370             k=s(k,l);Y.append(C(k)*(1. if N else 1.4))                                                                                                                                                  │
│   371         if Z is not None:                                                                                                                                                                               │
│   372             if j and z:Z=s(Z,z)                                                                                                                                                                         │
│   373             AL=1. if N or j else AX if a<b else AW;Y.append(C(Z)*AL)                                                                                                                                    │
│   374         AB=Ay(I)if A9>0 else None                                                                                                                                                                       │
│   375         if AB is not None:Y.append(C(AB)*A9)                                                                                                                                                            │
│   376         if not Y:return h(I,U,V)                                                                                                                                                                        │
│   377         G=C(A.hstack(Y))if B(Y)>1 else Y[0]                                                                                                                                                             │
│   378         if(not N or Ac)and P.perf_counter()-u<r*.45:G=Az(G,k=12 if 230<AI<330 else 12,alpha=.2 if 230<AI<330 else .1,iters=1)                                                                           │
│   379         if not N and P.perf_counter()-u<r*.55:                                                                                                                                                          │
│   380             AM=(36 if j else 16 if a<b else y)if 230<AI<330 else(AT if j else AU if a<b else y);AC=A_(G,dim=AM)                                                                                         │
│   381             if AC is not None:G=C(A.hstack([G,AC]))                                                                                                                                                     │
│   382         if P.perf_counter()-u>r:return h(I,U,V)                                                                                                                                                         │
│   383         AQ,AD=B0(G,k=16 if 230<AI<330 else A3);S,AE=(Ab,Ah)if N else B1(AQ);AR=J>A2                                                                                                                     │
│   384         if AR:                                                                                                                                                                                          │
│   385             m=A.sort(A.random.default_rng(0).choice(J,A2,replace=False));S=D(S,B(m)-1);AS=o(p(G[m],'average','cosine'),S,'maxclust').astype(A.int64);Aa=Q(n_neighbors=D(5,B(m)),metric='cosine').fit(G[ │
│   386             for n in K(0,J,5000):v,Ag=Aa.kneighbors(G[n:n+5000]);E[n:n+5000]=[A.bincount(B).argmax()for B in AS[Ag]]                                                                                    │
│   387             i=AD[:,-1]                                                                                                                                                                                  │
│   388         else:                                                                                                                                                                                           │
│   389             _L=p(G,'average','cosine')                                                                                                                                                                  │
│   390             if 230<AI<330:S,AE=28,0.2                                                                                                                                                                   │
│   391             S=D(S,J-1);E=o(_L,S,'maxclust').astype(A.int64);i=AD[:,-1]                                                                                                                                  │
│   392         e=A.fromiter((A4(A)for A in I),A.int16,J);E=A5(E,e)                                                                                                                                             │
│   393         if N:                                                                                                                                                                                           │
│   394             for v in K(2):AF=A.unique(E);Ai=C(A.stack([G[E==A].mean(0)for A in AF]));E=AF[(G@Ai.T).argmax(1)]                                                                                           │
│   395         elif a<b:E=Au(I,E)                                                                                                                                                                              │
│   396         if AE>0:                                                                                                                                                                                        │
│   397             W=F(J*AE)                                                                                                                                                                                   │
│   398             if W>0:                                                                                                                                                                                     │
│   399                 O=i.copy();O[e>0]=-1.                                                                                                                                                                   │
│   400                 if N or a<b:O=At(O,E,G,J)                                                                                                                                                               │
│   401                 M=A.argpartition(-O,W-1)[:W];M=M[O[M]>=0];E=E.copy();E[M]=A.arange(1000000,1000000+B(M))                                                                                                │
│   402         if not N and not 230<AI<330:E=RED(E,G,.77);_,E=A.unique(E,return_inverse=True)                                                                                                                  │
│   403         if not N and not 230<AI<330:E=MNN(E,G);_,E=A.unique(E,return_inverse=True)                                                                                                                      │
│   404         v,E=A.unique(E,return_inverse=True);X,f=[],0                                                                                                                                                    │
│   405         for w in V:                                                                                                                                                                                     │
│   406             if w:X.append(-1)                                                                                                                                                                           │
│   407             else:X.append(F(E[f]));f+=1                                                                                                                                                                 │
│   408         return X                                                                                                                                                                                        │
│   409     except R:return h(I,U,V)                                                                                                                                                                            │
│   410 def make_app()->m:                                                                                                                                                                                      │
│   411     A=m(title='Text Clustering Miner')                                                                                                                                                                  │
│   412     @A.get('/health')                                                                                                                                                                                   │
│   413     def B():return{'status':'healthy'}                                                                                                                                                                  │
│   414     @A.post('/cluster',response_model=Y)                                                                                                                                                                │
│   415     def C(request:Aq)->Y:                                                                                                                                                                               │
│   416         A=request                                                                                                                                                                                       │
│   417         if not A.texts:raise AH(status_code=400,detail='No texts provided')                                                                                                                             │
│   418         return Y(cluster_ids=cluster_texts(A.texts))                                                                                                                                                    │
│   419     return A                                                                                                                                                                                            │
│   420 if __name__=='__main__':f=AF.ArgumentParser();f.add_argument('--port',type=F,default=8001);f.add_argument('--host',type=G,default='0.0.0.0');AE=f.parse_args();uvicorn.run(make_app(),host=AE.host,port │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
