Fetching submission 180944...
Fetching code_submission_v1.py...
╭──────────────────────────────────────────────────────────────────────────────────────────── code_submission_v1.py ────────────────────────────────────────────────────────────────────────────────────────────╮
│     1 from __future__ import annotations                                                                                                                                                                      │
│     2 Ag='char_wb'                                                                                                                                                                                            │
│     3 Af='spectral'                                                                                                                                                                                           │
│     4 Ae='modularity'                                                                                                                                                                                         │
│     5 Ad='hdbscan'                                                                                                                                                                                            │
│     6 Ac='merge_mutual_nn'                                                                                                                                                                                    │
│     7 Ab='merge_scripts'                                                                                                                                                                                      │
│     8 Aa='fuzzy_spectral'                                                                                                                                                                                     │
│     9 AZ='fuzzy_smooth'                                                                                                                                                                                       │
│    10 AY='smooth_iters'                                                                                                                                                                                       │
│    11 AX='smooth_alpha'                                                                                                                                                                                       │
│    12 AW='smooth_k'                                                                                                                                                                                           │
│    13 AV='drop_components'                                                                                                                                                                                    │
│    14 AU='char_weight'                                                                                                                                                                                        │
│    15 AT='ppmi_cooccur'                                                                                                                                                                                       │
│    16 AS='ppmi_max_features'                                                                                                                                                                                  │
│    17 AR='ppmi_dim'                                                                                                                                                                                           │
│    18 AQ='lsa_dim'                                                                                                                                                                                            │
│    19 AP='w_distilled'                                                                                                                                                                                        │
│    20 AO='w_ppmi'                                                                                                                                                                                             │
│    21 AN='k_candidates'                                                                                                                                                                                       │
│    22 AM='k_fixed'                                                                                                                                                                                            │
│    23 AL='k_mode'                                                                                                                                                                                             │
│    24 AK='small_cluster_mode'                                                                                                                                                                                 │
│    25 AJ='noise_reclaim_thr'                                                                                                                                                                                  │
│    26 AI='noise_bucket_frac'                                                                                                                                                                                  │
│    27 AH='extra_noise_frac'                                                                                                                                                                                   │
│    28 AG='noise_mode'                                                                                                                                                                                         │
│    29 AF='reduce_dim'                                                                                                                                                                                         │
│    30 AE='reduce_mode'                                                                                                                                                                                        │
│    31 AD='hdbscan_epsilon'                                                                                                                                                                                    │
│    32 AC='hdbscan_selection'                                                                                                                                                                                  │
│    33 AB='hdbscan_min_samples'                                                                                                                                                                                │
│    34 AA='cluster_mode'                                                                                                                                                                                       │
│    35 A9='large_batch_noise_frac'                                                                                                                                                                             │
│    36 A8='large_batch_max_clusters'                                                                                                                                                                           │
│    37 A7='large_batch_threshold'                                                                                                                                                                              │
│    38 A6='time_budget'                                                                                                                                                                                        │
│    39 s='english'                                                                                                                                                                                             │
│    40 r='singleton'                                                                                                                                                                                           │
│    41 q='svd'                                                                                                                                                                                                 │
│    42 p='dedup_near_duplicates'                                                                                                                                                                               │
│    43 o='spectral_knn'                                                                                                                                                                                        │
│    44 n='min_cluster_size'                                                                                                                                                                                    │
│    45 m=enumerate                                                                                                                                                                                             │
│    46 e=ValueError                                                                                                                                                                                            │
│    47 X='cosine'                                                                                                                                                                                              │
│    48 U=' '                                                                                                                                                                                                   │
│    49 T=False                                                                                                                                                                                                 │
│    50 S=range                                                                                                                                                                                                 │
│    51 R=max                                                                                                                                                                                                   │
│    52 Q=Exception                                                                                                                                                                                             │
│    53 O=.0                                                                                                                                                                                                    │
│    54 N=list                                                                                                                                                                                                  │
│    55 M=True                                                                                                                                                                                                  │
│    56 K=min                                                                                                                                                                                                   │
│    57 J=bool                                                                                                                                                                                                  │
│    58 I=1.                                                                                                                                                                                                    │
│    59 F=str                                                                                                                                                                                                   │
│    60 E=len                                                                                                                                                                                                   │
│    61 D=None                                                                                                                                                                                                  │
│    62 C=float                                                                                                                                                                                                 │
│    63 B=int                                                                                                                                                                                                   │
│    64 import argparse as Ah,os,re as P,time as f                                                                                                                                                              │
│    65 for Ai in('OPENBLAS_NUM_THREADS','OMP_NUM_THREADS','MKL_NUM_THREADS','NUMEXPR_NUM_THREADS','VECLIB_MAXIMUM_THREADS'):os.environ.setdefault(Ai,'1')                                                      │
│    66 import numpy as A,sklearn,uvicorn                                                                                                                                                                       │
│    67 from fastapi import FastAPI,HTTPException as Aj                                                                                                                                                         │
│    68 from pydantic import BaseModel as t                                                                                                                                                                     │
│    69 from scipy.cluster.hierarchy import fcluster as a,linkage                                                                                                                                               │
│    70 from scipy.sparse import coo_matrix as g,csr_matrix as b                                                                                                                                                │
│    71 from scipy.sparse import hstack as h                                                                                                                                                                    │
│    72 from scipy.sparse.linalg import eigsh                                                                                                                                                                   │
│    73 from sklearn.cluster import HDBSCAN,MiniBatchKMeans as u                                                                                                                                                │
│    74 from sklearn.decomposition import TruncatedSVD as c                                                                                                                                                     │
│    75 from sklearn.feature_extraction.text import CountVectorizer as i                                                                                                                                        │
│    76 from sklearn.neighbors import NearestNeighbors as Y                                                                                                                                                     │
│    77 from sklearn.preprocessing import normalize as G                                                                                                                                                        │
│    78 sklearn.set_config(working_memory=128)                                                                                                                                                                  │
│    79 CONFIG={A6:74.,A7:8000,A8:100,A9:.2,n:25,AA:Ad,AB:15,AC:'eom',AD:O,AE:q,AF:80,o:25,AG:r,AH:O,AI:.5,AJ:O,AK:'noise',AL:Ae,AM:45,AN:(24,32,40,48,60,75,95,120),'w_lsa':I,AO:1.2,AP:.5,AQ:192,AR:128,AS:20 │
│    80 def configure(**A:object):                                                                                                                                                                              │
│    81     B=set(A)-set(CONFIG)                                                                                                                                                                                │
│    82     if B:raise KeyError(f"unknown config keys: {sorted(B)}")                                                                                                                                            │
│    83     CONFIG.update(A)                                                                                                                                                                                    │
│    84 def H(name:F,is_titles:J):                                                                                                                                                                              │
│    85     if is_titles:                                                                                                                                                                                       │
│    86         A='title_'+name                                                                                                                                                                                 │
│    87         if A in CONFIG:return CONFIG[A]                                                                                                                                                                 │
│    88     return CONFIG[name]                                                                                                                                                                                 │
│    89 L=-1                                                                                                                                                                                                    │
│    90 V=0                                                                                                                                                                                                     │
│    91 DISTILLED_BLOB='첛겖奀一甶꣑娄両于一丂嫵鑧剶뎞빝且댁鱳ꐾ羭뵍뢔逸燹綽娷貃몦벥矜덡剢댏己寻븦ꅐ遛鞉얄닆ꤠ雘泬鐞忪엡옊肱듒믬芠ꬲꖟ좽ꌱ쐧揙걻幓皞鍨쏼宝쳯됂멗瑴頀쉵己뎊熡딤ꔷ嗠뺛挴壚嫐궱铀飃忒觎몑쒮钠싘歺臈쓅뺓 │
│    92 Z=D                                                                                                                                                                                                     │
│    93 Ak=19968                                                                                                                                                                                                │
│    94 v=15                                                                                                                                                                                                    │
│    95 def Al(text:F):                                                                                                                                                                                         │
│    96     B=A=0;C=bytearray()                                                                                                                                                                                 │
│    97     for D in text:                                                                                                                                                                                      │
│    98         B=B<<v|ord(D)-Ak;A+=v                                                                                                                                                                           │
│    99         while A>=8:A-=8;C.append(B>>A&255)                                                                                                                                                              │
│   100     return bytes(C)                                                                                                                                                                                     │
│   101 def load_distilled():                                                                                                                                                                                   │
│   102     global Z                                                                                                                                                                                            │
│   103     if Z is not D:return Z                                                                                                                                                                              │
│   104     if not DISTILLED_BLOB:return                                                                                                                                                                        │
│   105     try:                                                                                                                                                                                                │
│   106         import lzma;E=lzma.LZMADecompressor().decompress(Al(DISTILLED_BLOB));H=E[:4]==b'SPRS';C=4 if H else 0;L=6 if H else 5;M=[B(A)for A in A.frombuffer(E[C:C+L*4],A.uint32)];C+=L*4;F,N,O,P,R=M[:5] │
│   107         if H:Y=A.frombuffer(E[C:C+G*4],A.uint32);C+=G*4;J=A.cumsum(Y.astype(A.int64))-1                                                                                                                 │
│   108         a=A.frombuffer(E[C:C+G*F],A.uint8).reshape(G,F);C+=G*F;b=A.frombuffer(E[C:C+G],A.uint8);I=A.concatenate([W[A][a[:,A]]for A in S(F)],axis=1);I=(I*X[b][:,D]).astype(A.float32)                   │
│   109         if J is D:K=I                                                                                                                                                                                   │
│   110         else:K=A.zeros((T,O),A.float32);K[J]=I                                                                                                                                                          │
│   111         Z=K,P,R;return Z                                                                                                                                                                                │
│   112     except Q:return                                                                                                                                                                                     │
│   113 def w(docs:N[F]):                                                                                                                                                                                       │
│   114     C=docs;I=load_distilled()                                                                                                                                                                           │
│   115     if I is D:return                                                                                                                                                                                    │
│   116     J,O,K=I                                                                                                                                                                                             │
│   117     try:                                                                                                                                                                                                │
│   118         from sklearn.feature_extraction.text import HashingVectorizer as L;M=[L(n_features=O,ngram_range=(1,2),analyzer='word',alternate_sign=T,norm=D,dtype=A.float32)]                                │
│   119         if K:M.append(L(n_features=K,ngram_range=(3,5),analyzer=Ag,alternate_sign=T,norm=D,dtype=A.float32))                                                                                            │
│   120         N=A.empty((E(C),J.shape[1]),A.float32)                                                                                                                                                          │
│   121         for B in S(0,E(C),4000):P=C[B:B+4000];F=[A.transform(P)for A in M];H=h(F).tocsr()if E(F)>1 else F[0];H.data=A.log1p(H.data).astype(A.float32);N[B:B+4000]=A.asarray(G(H)@J,dtype=A.float32)     │
│   122         return G(N)                                                                                                                                                                                     │
│   123     except Q:return                                                                                                                                                                                     │
│   124 Am=P.compile('https?://\\S+|www\\.\\S+')                                                                                                                                                                │
│   125 x=P.compile('@\\w+')                                                                                                                                                                                    │
│   126 An=P.compile('#(\\w+)')                                                                                                                                                                                 │
│   127 Ao=P.compile('^rt\\s+',P.IGNORECASE)                                                                                                                                                                    │
│   128 Ap=P.compile('(?<=[a-z0-9])(?=[A-Z])')                                                                                                                                                                  │
│   129 Aq=P.compile('(.)\\1{2,}')                                                                                                                                                                              │
│   130 Ar=P.compile('&\\w+;')                                                                                                                                                                                  │
│   131 As=P.compile('\\s+')                                                                                                                                                                                    │
│   132 At=P.compile('[!-/:-@\\[-`{-~]')                                                                                                                                                                        │
│   133 Au=P.compile("[^\\W\\d_][\\w\\-']*",P.UNICODE)                                                                                                                                                          │
│   134 Av=frozenset('a an the of for and or to in on with by from at as is are be been being am was were we our us you your i my me he she it they them his her their this that these those what which who who │
│   135 Aw=4000                                                                                                                                                                                                 │
│   136 def Ax(text:F,keep_case:J=T):                                                                                                                                                                           │
│   137     A=text                                                                                                                                                                                              │
│   138     if not isinstance(A,F):A=F(A)                                                                                                                                                                       │
│   139     A=Am.sub(U,A);A=Ao.sub(U,A);A=x.sub(U,A);A=An.sub('\\1',A);A=Ap.sub(U,A);A=Ar.sub(U,A);A=Aq.sub('\\1\\1',A);A=At.sub(U,A)                                                                           │
│   140     if not keep_case:A=A.lower()                                                                                                                                                                        │
│   141     return As.sub(U,A).strip()[:Aw]                                                                                                                                                                     │
│   142 def BG(text:F):return[A for A in(A.group(0).lower()for A in Au.finditer(text))if E(A)>2 and A not in Av]                                                                                                │
│   143 Ay=(1024,1327,1),(19968,40959,2),(12352,12543,2),(44032,55215,2),(1536,1791,3),(1424,1535,4),(3584,3711,5),(2304,2431,6)                                                                                │
│   144 def Az(text:F):                                                                                                                                                                                         │
│   145     A=[0]*7                                                                                                                                                                                             │
│   146     for C in text:                                                                                                                                                                                      │
│   147         D=ord(C)                                                                                                                                                                                        │
│   148         for(F,G,H)in Ay:                                                                                                                                                                                │
│   149             if F<=D<=G:A[H]+=1;break                                                                                                                                                                    │
│   150     B=R(S(1,7),key=lambda i:A[i]);return B if A[B]*8>=(E(text)or 1)else 0                                                                                                                               │
│   151 def A_(raw:N[F],cleaned:N[F]):F=[E(A)for A in cleaned];G=[A for A in F if A>=40];H=C(A.median(G if E(G)>=50 else F));D=raw[:2000];K=C(A.mean(['\n'in A for A in D]));L=C(A.mean(['http'in A.lower()or'w │
│   152 def y(counts,k1:C=3.,b:C=.75):B=counts;B=B.tocsr().astype(A.float32);E=A.asarray(B.sum(1)).ravel();G=R(C(E.mean()),1e-09);F=A.asarray((B>0).sum(0)).ravel();H=A.log(I+(B.shape[0]-F+.5)/(F+.5)).astype( │
│   153 def z(docs:N[F],is_titles:J=T):                                                                                                                                                                         │
│   154     F=docs;M=C(H(AU,is_titles));D=[]                                                                                                                                                                    │
│   155     try:D.append(y(i(ngram_range=(1,2),min_df=2,max_df=.5,max_features=60000,stop_words=s,dtype=A.float32).fit_transform(F)))                                                                           │
│   156     except e:0                                                                                                                                                                                          │
│   157     try:                                                                                                                                                                                                │
│   158         I=y(i(analyzer=Ag,ngram_range=(3,5),min_df=3,max_df=.5,max_features=20000,dtype=A.float32).fit_transform(F))                                                                                    │
│   159         if I.shape[1]>0:D.append(I*M)                                                                                                                                                                   │
│   160     except e:0                                                                                                                                                                                          │
│   161     if not D:return                                                                                                                                                                                     │
│   162     J=G(D[0]if E(D)==1 else h(D).tocsr());L=B(K(B(CONFIG[AQ]),J.shape[1]-1,E(F)-1))                                                                                                                     │
│   163     if L<2:return                                                                                                                                                                                       │
│   164     return G(c(L,random_state=V).fit_transform(J)).astype(A.float32)                                                                                                                                    │
│   165 def B0(docs:N[F],window:B=10):                                                                                                                                                                          │
│   166     h='ignore';H=docs                                                                                                                                                                                   │
│   167     try:J=i(min_df=3,stop_words=s,dtype=A.int32,max_features=B(CONFIG[AS]));J.fit(H)                                                                                                                    │
│   168     except e:return                                                                                                                                                                                     │
│   169     M=J.vocabulary_                                                                                                                                                                                     │
│   170     if E(M)<20:return                                                                                                                                                                                   │
│   171     N=E(M)                                                                                                                                                                                              │
│   172     if F(CONFIG[AT])=='document':P=J.transform(H);P.data=A.ones_like(P.data,dtype=A.float32);D=(P.T@P).tocsr();D.setdiag(O);D.eliminate_zeros()                                                         │
│   173     else:                                                                                                                                                                                               │
│   174         j=J.build_analyzer();L=[];U=[]                                                                                                                                                                  │
│   175         for k in H:                                                                                                                                                                                     │
│   176             X=[M[A]for A in j(k)if A in M]                                                                                                                                                              │
│   177             for(Y,Z)in m(X):                                                                                                                                                                            │
│   178                 for a in X[Y+1:Y+1+window]:L.append(Z);U.append(a);L.append(a);U.append(Z)                                                                                                              │
│   179         if not L:return                                                                                                                                                                                 │
│   180         D=g((A.ones(E(L),dtype=A.float32),(L,U)),shape=(N,N)).tocsr();D.sum_duplicates()                                                                                                                │
│   181     b=C(D.sum())                                                                                                                                                                                        │
│   182     if b<=0:return                                                                                                                                                                                      │
│   183     l=A.asarray(D.sum(axis=1)).ravel();n=A.asarray(D.sum(axis=0)).ravel();D=D.tocoo()                                                                                                                   │
│   184     with A.errstate(divide=h,invalid=h):Q=A.log(D.data*b/(l[D.row]*n[D.col]+1e-12)+1e-12)                                                                                                               │
│   185     Q[~A.isfinite(Q)]=O;S=Q>0                                                                                                                                                                           │
│   186     if not S.any():return                                                                                                                                                                               │
│   187     d=g((Q[S],(D.row[S],D.col[S])),shape=(N,N)).tocsr();o=B(K(B(CONFIG[AR]),R(2,K(d.shape)-1)));p=G(c(o,random_state=V).fit_transform(d));f=J.transform(H).astype(A.float32);q=A.log(E(H)/(I+A.asarray( │
│   188     if W.any():T[W]=A.random.RandomState(V).normal(size=(B(W.sum()),T.shape[1])).astype(A.float32)*.001                                                                                                 │
│   189     return T                                                                                                                                                                                            │
│   190 def B1(X:A.ndarray,n:B):                                                                                                                                                                                │
│   191     X=A.asarray(X,A.float32)                                                                                                                                                                            │
│   192     if n<1 or K(X.shape)<3:return G(X)                                                                                                                                                                  │
│   193     X=X-X.mean(0,keepdims=M);n=K(B(n),X.shape[1]-1,X.shape[0]-1)                                                                                                                                        │
│   194     if n<1:return G(X)                                                                                                                                                                                  │
│   195     C=c(n_components=n,random_state=V).fit(X);return G(X-C.inverse_transform(C.transform(X))).astype(A.float32)                                                                                         │
│   196 class A0:                                                                                                                                                                                               │
│   197     def __init__(A,budget:C):A.start=f.perf_counter();A.budget=budget                                                                                                                                   │
│   198     @property                                                                                                                                                                                           │
│   199     def elapsed(self):return f.perf_counter()-self.start                                                                                                                                                │
│   200     def used(A,fraction:C):return A.elapsed>=A.budget*fraction                                                                                                                                          │
│   201     def absolute(A,fraction:C):return A.start+A.budget*fraction                                                                                                                                         │
│   202 def B2(docs:N[F],is_titles:J,clock:A0):                                                                                                                                                                 │
│   203     K=docs;I=is_titles;F=[];L=C(H('w_lsa',I))                                                                                                                                                           │
│   204     if L>0:                                                                                                                                                                                             │
│   205         M=z(K,I)                                                                                                                                                                                        │
│   206         if M is not D:F.append(G(M)*L)                                                                                                                                                                  │
│   207     N=C(H(AO,I))                                                                                                                                                                                        │
│   208     if not clock.used(.55)and N>0:                                                                                                                                                                      │
│   209         J=B0(K,window=25 if I else 10)                                                                                                                                                                  │
│   210         if J is not D:J=B1(J,B(H(AV,I)));F.append(G(J)*N)                                                                                                                                               │
│   211     O=C(H(AP,I))                                                                                                                                                                                        │
│   212     if O>0:                                                                                                                                                                                             │
│   213         P=w(K)                                                                                                                                                                                          │
│   214         if P is not D:F.append(G(P)*O)                                                                                                                                                                  │
│   215     if not F:return                                                                                                                                                                                     │
│   216     return G(A.hstack(F)).astype(A.float32)if E(F)>1 else F[0]                                                                                                                                          │
│   217 def A1(Z:A.ndarray,k:B):                                                                                                                                                                                │
│   218     C=Z.shape[0];k=K(k,C-1)                                                                                                                                                                             │
│   219     if k<2:return                                                                                                                                                                                       │
│   220     try:B=Y(n_neighbors=k,metric=X).fit(Z).kneighbors_graph(Z,mode='connectivity')                                                                                                                      │
│   221     except Q:return                                                                                                                                                                                     │
│   222     B=(B+B.T>0).astype(A.float32);B.setdiag(O);B.eliminate_zeros();return B.tocsr()                                                                                                                     │
│   223 def A2(Z:A.ndarray,k:B):                                                                                                                                                                                │
│   224     B=Z.shape[0];k=K(k+1,B-1)                                                                                                                                                                           │
│   225     if k<3:return                                                                                                                                                                                       │
│   226     try:C,E=Y(n_neighbors=k,metric=X).fit(Z).kneighbors(Z)                                                                                                                                              │
│   227     except Q:return                                                                                                                                                                                     │
│   228     C,E=C[:,1:].astype(A.float32),E[:,1:];P=C[:,0:1];T=A.log2(R(C.shape[1],2)).astype(A.float32);F=A.full((B,1),1e-06,A.float32);G=A.full((B,1),1e3,A.float32);D=A.ones((B,1),A.float32);J=A.maximum(C- │
│   229     for a in S(32):D=.5*(F+G);U=A.exp(-J/A.maximum(D,1e-12)).sum(1,keepdims=M);L=U>T;G=A.where(L,D,G);F=A.where(L,F,D)                                                                                  │
│   230     V=A.exp(-J/A.maximum(D,1e-12)).astype(A.float32);W=A.repeat(A.arange(B),C.shape[1]);H=b((V.ravel(),(W,E.ravel())),shape=(B,B));N=H.T.tocsr();I=(H+N-H.multiply(N)).tocsr();I.setdiag(O);I.eliminate │
│   231 def B3(Z:A.ndarray,k:B,alpha:C,iters:B,fuzzy:J=T):                                                                                                                                                      │
│   232     E=iters;B=alpha;H=Z.shape[0]                                                                                                                                                                        │
│   233     if E<1 or B<=0:return Z                                                                                                                                                                             │
│   234     if fuzzy:                                                                                                                                                                                           │
│   235         J=A2(Z,k)                                                                                                                                                                                       │
│   236         if J is D:return Z                                                                                                                                                                              │
│   237         L,M=J;F=A.asarray(L.sum(1)).ravel();F[F<=0]=I;P=L.multiply((I/F)[:,D]).tocsr()                                                                                                                  │
│   238         for M in S(E):Z=G((I-B)*Z+B*(P@Z))                                                                                                                                                              │
│   239         return A.asarray(Z,A.float32)                                                                                                                                                                   │
│   240     N=K(k+1,H-1)                                                                                                                                                                                        │
│   241     if N<2:return Z                                                                                                                                                                                     │
│   242     try:R=Y(n_neighbors=N,metric=X).fit(Z).kneighbors(Z)[1][:,1:]                                                                                                                                       │
│   243     except Q:return Z                                                                                                                                                                                   │
│   244     for M in S(E):                                                                                                                                                                                      │
│   245         O=A.empty_like(Z)                                                                                                                                                                               │
│   246         for C in S(0,H,2000):O[C:C+2000]=Z[R[C:C+2000]].mean(axis=1)                                                                                                                                    │
│   247         Z=G((I-B)*Z+B*O)                                                                                                                                                                                │
│   248     return Z.astype(A.float32)                                                                                                                                                                          │
│   249 def B4(Z:A.ndarray,dim:B,k:B,fuzzy:J=M):                                                                                                                                                                │
│   250     F=Z.shape[0]                                                                                                                                                                                        │
│   251     if F<50 or dim<2:return                                                                                                                                                                             │
│   252     B=D                                                                                                                                                                                                 │
│   253     if fuzzy:                                                                                                                                                                                           │
│   254         L=A2(Z,k)                                                                                                                                                                                       │
│   255         if L is not D:B=L[0]                                                                                                                                                                            │
│   256     if B is D:B=A1(Z,k)                                                                                                                                                                                 │
│   257     if B is D:return                                                                                                                                                                                    │
│   258     try:                                                                                                                                                                                                │
│   259         H=A.asarray(B.sum(axis=1)).ravel();H[H<=0]=I;M=(I/A.sqrt(H)).astype(A.float32);J=B.multiply(M[:,D]).multiply(M[D,:]);J=b(J,dtype=A.float32);P=K(dim+1,F-2);C,E=eigsh(J,k=P,which='LA',v0=A.ones │
│   260         if E.shape[1]<2:return                                                                                                                                                                          │
│   261         R=E*A.maximum(C,O)[D,:];return G(R.astype(A.float32))                                                                                                                                           │
│   262     except Q:return                                                                                                                                                                                     │
│   263 def B5(Z:A.ndarray,is_titles:J=T):                                                                                                                                                                      │
│   264     E=is_titles;I=F(H(AE,E));C=B(H(AF,E))                                                                                                                                                               │
│   265     if I==Af:                                                                                                                                                                                           │
│   266         L=B4(Z,C,B(H(o,E)),J(H(Aa,E)))                                                                                                                                                                  │
│   267         if L is not D:return L                                                                                                                                                                          │
│   268         I=q                                                                                                                                                                                             │
│   269     if I==q:                                                                                                                                                                                            │
│   270         C=K(C,Z.shape[1]-1,Z.shape[0]-1)                                                                                                                                                                │
│   271         if C>=2:return G(c(C,random_state=V).fit_transform(Z)).astype(A.float32)                                                                                                                        │
│   272     return Z                                                                                                                                                                                            │
│   273 def B6(E:A.ndarray,min_cluster_size:B,is_titles:J=T):                                                                                                                                                   │
│   274     H=min_cluster_size;I=E.shape[0]                                                                                                                                                                     │
│   275     if I<H*2:return                                                                                                                                                                                     │
│   276     J=CONFIG[AB];K=C(CONFIG[AD])                                                                                                                                                                        │
│   277     try:G=HDBSCAN(min_cluster_size=H,min_samples=D if J is D else B(J),metric='euclidean',cluster_selection_method=F(CONFIG[AC]),cluster_selection_epsilon=K,copy=M).fit_predict(A.ascontiguousarray(E, │
│   278     except Q:return                                                                                                                                                                                     │
│   279     G=A.asarray(G,A.int64)                                                                                                                                                                              │
│   280     if(G>=0).sum()<.2*I:return                                                                                                                                                                          │
│   281     return G                                                                                                                                                                                            │
│   282 def B7(graph:b,labels:A.ndarray):                                                                                                                                                                       │
│   283     G=graph;D=labels;E=G.tocoo();F=C(E.data.sum())                                                                                                                                                      │
│   284     if F<=0:return-I                                                                                                                                                                                    │
│   285     H=D[E.row]==D[E.col];J=C(E.data[H].sum());K=A.asarray(G.sum(axis=1)).ravel();L=B(D.max())+1;M=A.bincount(D,weights=K,minlength=L);return J/F-C(((M/F)**2).sum())/4.                                 │
│   286 def B8(E:A.ndarray,deadline:C):                                                                                                                                                                         │
│   287     I='maxclust';C=E.shape[0];H=linkage(E,'average',X);M=F(CONFIG[AL]);J=R(2,K(B(CONFIG[AM]),C-1))                                                                                                      │
│   288     if M=='fixed':return a(H,J,I).astype(A.int64)-1                                                                                                                                                     │
│   289     N=A1(E,B(CONFIG[o]))                                                                                                                                                                                │
│   290     if N is D or M!=Ae:return a(H,J,I).astype(A.int64)-1                                                                                                                                                │
│   291     L=[B(A)for A in CONFIG[AN]if A<C]                                                                                                                                                                   │
│   292     if not L:L=sorted({R(2,C//25),R(2,C//10),R(2,C//4)})                                                                                                                                                │
│   293     G=D;O=-A.inf                                                                                                                                                                                        │
│   294     for S in L:                                                                                                                                                                                         │
│   295         if f.perf_counter()>deadline and G is not D:break                                                                                                                                               │
│   296         P=a(H,S,I).astype(A.int64)-1;Q=B7(N,P)                                                                                                                                                          │
│   297         if Q>O:O,G=Q,P                                                                                                                                                                                  │
│   298     if G is D:G=a(H,J,I).astype(A.int64)-1                                                                                                                                                              │
│   299     return G                                                                                                                                                                                            │
│   300 def W(labels:A.ndarray):                                                                                                                                                                                │
│   301     B=labels;B=A.asarray(B,A.int64);D=A.full(B.shape,L,A.int64);C=B!=L                                                                                                                                  │
│   302     if C.any():F,E=A.unique(B[C],return_inverse=M);D[C]=E                                                                                                                                               │
│   303     return D                                                                                                                                                                                            │
│   304 def B9(labels:A.ndarray,sids:A.ndarray,lo:C=.02,hi:C=.45,purity:C=.55,min_size:B=3):                                                                                                                    │
│   305     D=labels.copy()                                                                                                                                                                                     │
│   306     for H in S(1,7):                                                                                                                                                                                    │
│   307         I=sids==H;J=C(I.mean())                                                                                                                                                                         │
│   308         if J<lo or J>hi:continue                                                                                                                                                                        │
│   309         F=[]                                                                                                                                                                                            │
│   310         for G in A.unique(D[I]):                                                                                                                                                                        │
│   311             if G==L:continue                                                                                                                                                                            │
│   312             K=D==G                                                                                                                                                                                      │
│   313             if K.sum()>=min_size and(sids[K]==H).mean()>=purity:F.append(B(G))                                                                                                                          │
│   314         if E(F)>=2:D[A.isin(D,F)]=F[0]                                                                                                                                                                  │
│   315     return D                                                                                                                                                                                            │
│   316 def j(labels:A.ndarray,Z:A.ndarray):                                                                                                                                                                    │
│   317     C=labels;B=A.array([A for A in A.unique(C)if A!=L],A.int64)                                                                                                                                         │
│   318     if B.size==0:return B,A.zeros((0,Z.shape[1]),A.float32)                                                                                                                                             │
│   319     D=A.stack([Z[C==A].mean(0)for A in B]);return B,G(D).astype(A.float32)                                                                                                                              │
│   320 def BA(labels:A.ndarray,Z:A.ndarray,floor:B,mode:F):                                                                                                                                                    │
│   321     F=labels;D=floor                                                                                                                                                                                    │
│   322     if mode=='none'or D<2:return F                                                                                                                                                                      │
│   323     B=F.copy();H,I=A.unique(B[B!=L],return_counts=M);C=H[I<D]                                                                                                                                           │
│   324     if C.size==0:return B                                                                                                                                                                               │
│   325     if mode=='noise':B[A.isin(B,C)]=L;return B                                                                                                                                                          │
│   326     E=H[I>=D]                                                                                                                                                                                           │
│   327     if E.size==0:B[A.isin(B,C)]=L;return B                                                                                                                                                              │
│   328     K=G(A.stack([Z[B==A].mean(0)for A in E])).astype(A.float32);J=A.isin(B,C);B[J]=E[(Z[J]@K.T).argmax(1)];return B                                                                                     │
│   329 def BB(labels:A.ndarray,Z:A.ndarray,thr:C=.85,max_size:B=60,rounds:B=3):                                                                                                                                │
│   330     C=labels.copy()                                                                                                                                                                                     │
│   331     for R in S(rounds):                                                                                                                                                                                 │
│   332         N,O=A.unique(C[C!=L],return_counts=M);D=N[O<=max_size]                                                                                                                                          │
│   333         if D.size<2:break                                                                                                                                                                               │
│   334         H=G(A.stack([Z[C==A].mean(0)for A in D]))                                                                                                                                                       │
│   335         try:P,J=Y(n_neighbors=2,metric=X).fit(H).kneighbors(H)                                                                                                                                          │
│   336         except Q:break                                                                                                                                                                                  │
│   337         K=T                                                                                                                                                                                             │
│   338         for E in S(D.size):                                                                                                                                                                             │
│   339             F=B(J[E,1])                                                                                                                                                                                 │
│   340             if I-P[E,1]>=thr and B(J[F,1])==E and D[E]<D[F]:C[C==D[F]]=D[E];K=M                                                                                                                         │
│   341         if not K:break                                                                                                                                                                                  │
│   342         C=W(C)                                                                                                                                                                                          │
│   343     return C                                                                                                                                                                                            │
│   344 def BC(Z:A.ndarray,labels:A.ndarray,k:B=12):                                                                                                                                                            │
│   345     E=labels;F=Z.shape[0]                                                                                                                                                                               │
│   346     try:J=Y(n_neighbors=K(k+1,F-1),metric=X).fit(Z).kneighbors(Z)[0][:,1:];D=J[:,-1].astype(A.float32)                                                                                                  │
│   347     except Q:D=A.zeros(F,A.float32)                                                                                                                                                                     │
│   348     G,L=j(E,Z)                                                                                                                                                                                          │
│   349     if G.size:                                                                                                                                                                                          │
│   350         M={B(C):A for(A,C)in m(G)};H=A.array([M.get(B(A),-1)for A in E]);C=H>=0                                                                                                                         │
│   351         if C.any():N=A.einsum('ij,ij->i',Z[C],L[H[C]]);D[C]=D[C]+(I-N).astype(A.float32)                                                                                                                │
│   352     return D                                                                                                                                                                                            │
│   353 def BD(labels:A.ndarray,Z:A.ndarray,sids:A.ndarray,is_titles:J=T):                                                                                                                                      │
│   354     h='graded';S=is_titles;T=F(H(AG,S));G=labels.copy();U=C(H(AH,S));V=D                                                                                                                                │
│   355     if U>0 or T==h:V=BC(Z,G)                                                                                                                                                                            │
│   356     if U>0:                                                                                                                                                                                             │
│   357         i=G.size;M=B(i*U)                                                                                                                                                                               │
│   358         if M>0:                                                                                                                                                                                         │
│   359             P=V.copy();P[sids>0]=-I;P[G==L]=-I;k=B((P>=0).sum());M=K(M,k)                                                                                                                               │
│   360             if M>0:b=A.argpartition(-P,M-1)[:M];G[b[P[b]>=0]]=L                                                                                                                                         │
│   361     J=G==L                                                                                                                                                                                              │
│   362     if not J.any():return W(G)                                                                                                                                                                          │
│   363     if T=='none':                                                                                                                                                                                       │
│   364         Q,X=j(G,Z)                                                                                                                                                                                      │
│   365         if Q.size:G[J]=Q[(Z[J]@X.T).argmax(1)]                                                                                                                                                          │
│   366         return W(G)                                                                                                                                                                                     │
│   367     Y=C(H(AJ,S))                                                                                                                                                                                        │
│   368     if Y>0:                                                                                                                                                                                             │
│   369         Q,X=j(G,Z)                                                                                                                                                                                      │
│   370         if Q.size:                                                                                                                                                                                      │
│   371             c=Z[J]@X.T;l,d=c.argmax(1),c.max(1);m=A.where(J)[0][d>=Y];G[m]=Q[l[d>=Y]];J=G==L                                                                                                            │
│   372             if not J.any():return W(G)                                                                                                                                                                  │
│   373     G=W(G);N=B(G.max())+1 if(G!=L).any()else 0                                                                                                                                                          │
│   374     if T==r:G[J]=A.arange(N,N+B(J.sum()));return G                                                                                                                                                      │
│   375     if T==h:a=A.flatnonzero(J);n=C(H(AI,S));e=B(round(E(a)*K(R(n,O),I)));f=a[A.argsort(-V[a],kind='stable')];G[f[:e]]=N;g=f[e:];G[g]=A.arange(N+1,N+1+E(g));return G                                    │
│   376     G[J]=N;return G                                                                                                                                                                                     │
│   377 def A3(labels:A.ndarray,docs:N[F]):                                                                                                                                                                     │
│   378     D={}                                                                                                                                                                                                │
│   379     for(I,J)in m(docs):                                                                                                                                                                                 │
│   380         F=U.join(J.split()[:14])                                                                                                                                                                        │
│   381         if E(F)<25:continue                                                                                                                                                                             │
│   382         D.setdefault(F,[]).append(I)                                                                                                                                                                    │
│   383     B=labels.copy()                                                                                                                                                                                     │
│   384     for C in D.values():                                                                                                                                                                                │
│   385         if E(C)<2:continue                                                                                                                                                                              │
│   386         G=B[C];H=G[G!=L]                                                                                                                                                                                │
│   387         if H.size==0:continue                                                                                                                                                                           │
│   388         K,N=A.unique(H,return_counts=M);B[C]=K[N.argmax()]                                                                                                                                              │
│   389     return B                                                                                                                                                                                            │
│   390 def k(docs:N[F]):                                                                                                                                                                                       │
│   391     B=docs                                                                                                                                                                                              │
│   392     try:                                                                                                                                                                                                │
│   393         C=z(B)                                                                                                                                                                                          │
│   394         if C is D:raise e('no features')                                                                                                                                                                │
│   395         F=R(2,K(60,E(B)//40));return u(F,random_state=V,n_init=3).fit_predict(C).astype(A.int64)                                                                                                        │
│   396     except Q:return A.zeros(E(B),A.int64)                                                                                                                                                               │
│   397 def BE(docs:N[F]):                                                                                                                                                                                      │
│   398     H=docs                                                                                                                                                                                              │
│   399     try:                                                                                                                                                                                                │
│   400         from sklearn.feature_extraction.text import HashingVectorizer as S;F=S(n_features=32768,ngram_range=(1,2),analyzer='word',stop_words=s,alternate_sign=T,norm=D,dtype=A.float32).transform(H);F. │
│   401         if M is not D:J=h([F,b(M*2.)],format='csr')                                                                                                                                                     │
│   402         N=E(H);L=R(2,K(B(A.sqrt(N/2.)),B(CONFIG[A8])));O=u(L,random_state=V,n_init=3,batch_size=2048,max_iter=100,max_no_improvement=10);P=O.fit_predict(J).astype(A.int64);I=B(N*C(CONFIG[A9]))        │
│   403         if I>0:U=O.transform(J).min(axis=1);W=A.argpartition(-U,I-1)[:I];P[W]=A.arange(L,L+I)                                                                                                           │
│   404         return P                                                                                                                                                                                        │
│   405     except Q:return k(H)                                                                                                                                                                                │
│   406 def d(labels:A.ndarray,empty_mask:N[J]):                                                                                                                                                                │
│   407     A=[];C=0                                                                                                                                                                                            │
│   408     for D in empty_mask:                                                                                                                                                                                │
│   409         if D:A.append(L)                                                                                                                                                                                │
│   410         else:A.append(B(labels[C]));C+=1                                                                                                                                                                │
│   411     return A                                                                                                                                                                                            │
│   412 def cluster_texts(texts:N[F]):                                                                                                                                                                          │
│   413     T=texts;L=A0(C(CONFIG[A6]));U=E(T)                                                                                                                                                                  │
│   414     if U<3:return N(S(U))                                                                                                                                                                               │
│   415     V=[Ax(A)for A in T];O=[E(A)==0 for A in V];I=[A for(A,B)in zip(V,O,strict=M)if not B]                                                                                                               │
│   416     if E(I)<3:return[0]*U                                                                                                                                                                               │
│   417     try:                                                                                                                                                                                                │
│   418         X=E(I);K,a=A_(T,I)                                                                                                                                                                              │
│   419         if X>B(CONFIG[A7]):                                                                                                                                                                             │
│   420             G=BE(I)                                                                                                                                                                                     │
│   421             if J(CONFIG[p]):G=A3(G,I)                                                                                                                                                                   │
│   422             return d(W(G),O)                                                                                                                                                                            │
│   423         P=B2(I,K,L)                                                                                                                                                                                     │
│   424         if P is D:return d(k(I),O)                                                                                                                                                                      │
│   425         if not L.used(.7):P=B3(P,B(H(AW,K)),C(H(AX,K)),B(H(AY,K)),J(H(AZ,K)))                                                                                                                           │
│   426         R=P if L.used(.78)else B5(P,K);Z=F(CONFIG[AA]);G=D                                                                                                                                              │
│   427         if Z==Ad:G=B6(R,B(H(n,K)),K)                                                                                                                                                                    │
│   428         if G is D:G=B8(R,L.absolute(.88))                                                                                                                                                               │
│   429         G=A.asarray(G,A.int64);Y=A.fromiter((Az(A)for A in I),A.int16,X)                                                                                                                                │
│   430         if J(CONFIG[Ab]):G=B9(G,Y)                                                                                                                                                                      │
│   431         G=BA(G,R,B(H(n,K)),F(CONFIG[AK]))                                                                                                                                                               │
│   432         if J(CONFIG[Ac])and not L.used(.95):G=BB(G,R)                                                                                                                                                   │
│   433         G=BD(G,R,Y,K)                                                                                                                                                                                   │
│   434         if J(CONFIG[p]):G=A3(G,I)                                                                                                                                                                       │
│   435         G=W(G);return d(G,O)                                                                                                                                                                            │
│   436     except Q:return d(k(I),O)                                                                                                                                                                           │
│   437 class BF(t):texts:N[F]                                                                                                                                                                                  │
│   438 class A4(t):cluster_ids:N[B]                                                                                                                                                                            │
│   439 def make_app():                                                                                                                                                                                         │
│   440     A=FastAPI(title='Text Clustering Miner')                                                                                                                                                            │
│   441     @A.get('/health')                                                                                                                                                                                   │
│   442     def B():return{'status':'healthy'}                                                                                                                                                                  │
│   443     @A.post('/cluster',response_model=A4)                                                                                                                                                               │
│   444     def C(request:BF):                                                                                                                                                                                  │
│   445         A=request                                                                                                                                                                                       │
│   446         if not A.texts:raise Aj(status_code=400,detail='No texts provided')                                                                                                                             │
│   447         return A4(cluster_ids=cluster_texts(A.texts))                                                                                                                                                   │
│   448     return A                                                                                                                                                                                            │
│   449 if __name__=='__main__':l=Ah.ArgumentParser();l.add_argument('--port',type=B,default=8001);l.add_argument('--host',type=F,default='0.0.0.0');A5=l.parse_args();uvicorn.run(make_app(),host=A5.host,port │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
